/**
 * Content revision of `assets/agent-teams/`, generated by
 * `node scripts/art-revision.mjs --write` — do not edit by hand.
 *
 * Every artwork URL carries it as `?v=`, so redrawing a pack changes the URL
 * instead of leaving browsers on the previously cached bytes. `pnpm build` and
 * `scripts/verify.mjs` re-derive the value with `--check` and fail on a stale
 * constant, which is what keeps the pair honest.
 */
export const ART_REVISION = '5a90736f927c'
